import os
import random

os.system('clear')

print('0 ) Checks')
print(' ')
print('Please make sure you are running this tool as root on a Linux system.')
print('To exit, simply push Ctrl+C at any time.')
print(' ')
print('Press (almost) any key to continue.')
gopastchecks = raw_input('')

os.system('clear')

print('1 ) SMB Server/Share')
print(' ')
print('Example: \\\expensivenas\documents')
server = raw_input('>> ')

os.system('clear')

print('2 ) Mount Point')
print(' ')
print('Example: /media/nas-documents')
print('[i] The folder name here will be what the share shows up as')
mount_point = raw_input('>> ')

os.system('clear')

rint = random.randint(0,9)
rint = str(rint)


crs = open('/usr/.crs' + rint, 'a')
print('3 ) Credentials')
print(' ')
crsusr = raw_input('Username: ')
crspsw = raw_input('Password: ')
crs.write('username=')
crs.write(crsusr)
crs.write('\n')
crs.write('password=')
crs.write(crspsw)
os.system('clear')

print('4 ) GID')
print(' ')
print('Example: 1234')
print('[i] To find your GID, follow the steps here: http://bit.ly/GID-UID')
gid = raw_input('>> ')

os.system('clear')

print('5 ) UID')
print(' ')
print('Example: 4321')
print('[i] To find your UID, follow the steps here: http://bit.ly/GID-UID')
uid = raw_input('>> ')

os.system('clear')

print server
print mount_point
print gid
print uid

print(' ')

print('Is this OK?')
print('Enter to continue, Ctrl+C to cancel and exit.')
isok = raw_input('')

os.system('clear')

print('6 ) Doing the thing!')
print(' ')
print('Installing CIFS if required')
os.system('apt-get --yes --force-yes install cifs-utils')
print(' ')
print('Opening file')
# This is probably the worst way to do this, but it works so I don't care
fstab = open('/etc/fstab', 'a')
print('Writing newline')
fstab.write('\n')
os.system('clear')
print('Writing server/share')
fstab.write(server)
os.system('clear')
print('Writing a space')
fstab.write(' ')
os.system('clear')
print('Creating the mount point folder in case it doesn\'t exist')
#os.makedirs(mount_point)
os.system('clear')
print('Writing the mount point')
fstab.write(mount_point)
os.system('clear')
print('Writing the filesystem type')
fstab.write(' cifs ')
os.system('clear')
print('Writing username')
fstab.write('username=')
fstab.write(crsusr)
os.system('clear')
print('Writing a comma')
fstab.write(',')
os.system('clear')
print('Writing password')
fstab.write('password=')
fstab.write(crspsw)
os.system('clear')
print('Writing another comma')
fstab.write(',')
os.system('clear')
print('Writing charset')
fstab.write(',iocharset=utf8,gid=')
os.system('clear')
print('Writing GID')
fstab.write(gid)
os.system('clear')
print('Writing UID prefix')
fstab.write(',uid=')
os.system('clear')
print('Writing UID')
fstab.write(uid)
os.system('clear')
print('Writing final bits')
fstab.write(',file_mode=0777,dir_mode=0777 0 0')
os.system('clear')
print('Attempting to mount all drives')
os.system('mount -a')
os.system('clear')
print('Fingers crossed, the file should be updated!')
print('You may need to run "sudo mount -a" manually to access the share.')
