esc=`echo -en "\033"`
red="${esc}[;91m"
green="${esc}[;92m"
white="${esc}[;97m"
cyan="${esc}[;96m"

echo "${green}`.::///+:/-.        --///+//-:``       "
echo "${green} `+oooooooooooo:   `+oooooooooooo:     "
echo "${green}  /oooo++//ooooo:  ooooo+//+ooooo.     "
echo "${green}  `+ooooooo:-:oo-  +o+::/ooooooo:      "
echo "${green}   `:oooooooo+``    `.oooooooo+-       "
echo "${green}     `:++ooo/.        :+ooo+/.`        "
echo "${red}        ...`  `.----.` ``..              "
echo "${red}     .::::-``:::::::::.`-:::-`          ${cyan}______ _     "
echo "${red}    -:::-`   .:::::::-`  `-:::-         ${cyan}| ___ (_)    "
echo "${red}   `::.  `.--.`  `` `.---.``.::`        ${cyan}| |_/ /_     "
echo "${red}       .::::::::`  -::::::::` `         ${cyan}|  __/| |    "
echo "${red} .::` .:::::::::- `::::::::::``::.      ${cyan}| |   | |    "
echo "${red}:::` ::::::::::.  ::::::::::.`:::-      ${cyan}|_|   |_|    "
echo "${red} ::::  -::::::::.   `-::::::::  ::::    ${white} ___________   "
echo "${red}-::-   .-:::-.``....``.-::-.   -::-     ${white}|____ | ___ \  "
echo "${red} .. ``       .::::::::.     `..`..      ${white}    / / |_/ /  "
echo "${red}   -:::-`   -::::::::::`  .:::::`       ${white}    \ \ ___ \  "
echo "${red}   :::::::` -::::::::::` :::::::.       ${white}.___/ / |_/ /  "
echo "${red}   .:::::::  -::::::::. ::::::::        ${white}\____/\____/   "
echo "${red}   `-:::::`   ..--.`   ::::::.           "
echo "${red}      `...`  `...--..`  `...`            "
echo "${red}            .::::::::::                  "
echo "${red}             `.-::::-`                   "
echo "${white}"
